name: quotepicture
description: Application pour générer des citations avec des images

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cached_network_image: ^3.2.3
  share_plus: ^6.3.1
  path_provider: ^2.0.15
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:
  - .env